# Generated by Django 2.1.5 on 2020-07-27 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post1', '0003_auto_20200727_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 7, 15, 4, 783704, tzinfo=utc)),
        ),
    ]
