# Generated by Django 2.1.5 on 2020-07-27 07:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post1', '0005_auto_20200727_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slice_location',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 7, 33, 11, 932417, tzinfo=utc)),
        ),
    ]
