# Generated by Django 2.1.5 on 2020-07-28 00:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post1', '0010_auto_20200727_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 0, 37, 16, 34771, tzinfo=utc)),
        ),
    ]
