# Generated by Django 2.1.5 on 2020-07-28 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post1', '0013_auto_20200728_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 9, 6, 27, 900729, tzinfo=utc)),
        ),
    ]
