# Generated by Django 2.1.5 on 2020-07-28 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post1', '0014_auto_20200728_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 15, 36, 18, 232112, tzinfo=utc)),
        ),
    ]
