# Generated by Django 2.1.5 on 2020-07-29 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post1', '0015_auto_20200729_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 1, 32, 8, 948857, tzinfo=utc)),
        ),
    ]
