# Generated by Django 2.1.5 on 2020-07-31 00:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post1', '0016_auto_20200729_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 0, 48, 57, 784776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.IntegerField(choices=[(0, '남자'), (1, '여자')], default=0),
        ),
    ]
